/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed": "#0f0069",
        "surface-variant": "#d8e3fb",
        "on-primary-container": "#dad7ff",
        "secondary": "#006c49",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d8e3fb",
        "background": "#f9f9ff",
        "on-secondary": "#ffffff",
        "primary": "#3525cd",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005236",
        "tertiary-container": "#885500",
        "inverse-surface": "#263143",
        "secondary-fixed-dim": "#4edea3",
        "outline-variant": "#c7c4d8",
        "surface-tint": "#4d44e3",
        "on-tertiary-container": "#ffd4a4",
        "inverse-primary": "#c3c0ff",
        "secondary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#00714d",
        "on-primary": "#ffffff",
        "surface-bright": "#f9f9ff",
        "on-secondary-fixed": "#002113",
        "inverse-on-surface": "#ecf1ff",
        "on-background": "#111c2d",
        "on-tertiary-fixed": "#2a1700",
        "outline": "#777587",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-high": "#dee8ff",
        "on-tertiary-fixed-variant": "#653e00",
        "primary-fixed": "#e2dfff",
        "primary-fixed-dim": "#c3c0ff",
        "surface-dim": "#cfdaf2",
        "on-surface": "#111c2d",
        "tertiary": "#684000",
        "primary-container": "#4f46e5",
        "error": "#ba1a1a",
        "surface": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "tertiary-fixed": "#ffddb8",
        "secondary-container": "#6cf8bb",
        "on-surface-variant": "#464555",
        "surface-container": "#e7eeff",
        "on-primary-fixed-variant": "#3323cc",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1.5rem",
        "container-max": "1280px",
        "p-xl": "3rem",
        "p-lg": "2rem",
        "p-sm": "1rem",
        "margin-page": "2rem",
        "p-md": "1.5rem",
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "600" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
